name: Generate installer

on: 
  workflow_dispatch:
    inputs:
      pillow_v:
        description: 'Pillow version'
        type: string
        required: true
      neo_v:
        description: 'NeoForge version'
        type: string
        required: true
      quilt_v:
        description: 'Quilt Loader version'
        type: string
        required: true
      do_release:
        description: 'Do release?'
        type: boolean
        required: true
jobs:
  gen: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: PillowMC/pillow-install-meta
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Generate installer
        run: |
          wget https://maven.neoforged.net/releases/net/neoforged/neoforge/${{ inputs.neo_v }}/neoforge-${{ inputs.neo_v }}-installer.jar
          ./geninstaller.sh neoforge-${{ inputs.neo_v }}-installer.jar pillow-${{ inputs.pillow_v }}-installer.jar ${{ inputs.pillow_v }} ${{ inputs.quilt_v }}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: pillow-${{ inputs.pillow_v }}-installer.jar
      - name: Release
        uses: softprops/action-gh-release@v2
        if: inputs.do_release
        with:
          tag_name: v${{ inputs.pillow_v }}
          files: pillow-${{ inputs.pillow_v }}-installer.jar
          body: Installer is from NeoForge ${{ inputs.neo_v }}, with Quilt Loader ${{ inputs.quilt_v }}.